- pipeline.id: imdb-pipeline
  path.config: "/root/api/configs/logstash/imdb.movies.titles.cfg"
  pipeline.workers: 3
- pipeline.id: tmdb-pipeline
  path.config: "/root/api/configs/logstash/tmdb.movies.titles.cfg"
  queue.type: persisted
