- pipeline.id: imdb-pipeline
  path.config: "/root/api/imdb.movies.titles.cfg"
  pipeline.workers: 3
- pipeline.id: tmdb-pipeline
  path.config: "/root/api/tmdb.movies.titles.cfg"
  queue.type: persisted
